name: Kyndryl-Continuous-Delivery-Demo
on:
  push:
    branches:
    - master
jobs:
  build:
    env:
      NORIEGADOCKER_DOCKER_USERNAME: noriegadocker
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: Setup Java 11
      uses: actions/setup-java@v4.0.0
      with:
        distribution: zulu
        java-version: '11'
    - name: Run maven
      run: mvn --file pom.xml package
      env:
        MAVEN_OPTS: "-Xmx3072m"
    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action@v2.12.0
      if: always()
      with:
        junit_files: "**/target/site/jacoco/index.html"
    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action@v2.12.0
      if: always()
      with:
        comment_title: Resultados Testing
        junit_files: "**/TEST-*.xml"
    - name: Docker Image Build and Push
      uses: docker/login-action@v3.0.0
      with:
        username: "${{ env.NORIEGADOCKER_DOCKER_USERNAME }}"
        password: "${{ secrets.NORIEGADOCKER_DOCKER_PASSWORD }}"
    - name: Docker Image Build and Push
      run: docker build ./ --file "Dockerfile" -t noriegadocker/kyndryl-workshop-ci:${{ github.run_id }}
    - name: Docker Image Build and Push
      run: docker push noriegadocker/kyndryl-workshop-ci:${{ github.run_id }}
